### ISSUE TITLE
Explorer: `id` checkbox is always selected

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#10]
When toggling the task `id` on a new project with the field tool on the left, the checkbox never becomes unchecked, though the code is updated. Other fields work fine.

**Comment by mpscholten** [comment]
I think this only happens if there's no other checkbox selected, e.g. a query like `{ users }` instead of `{ users { id } }`. A query like that is invalid GraphQL and therefore this is likely the expected behaviour of GraphiQL

**Comment by jeyj0** [comment]
Nope. Fresh container, going straight to the explorer, this is what happens:

1. selected fields on the left: `tasks.id`; query code: `{
  tasks {
    id
  }
}`
2. click on `tasks.title` on the left: both `tasks.id` and `tasks.title` appear checked, the query code updates accordingly
3. click on `tasks.id` on the left: both `tasks.id` and `tasks.title` appear checked, the query code updates to: `{
  tasks {
    title
  }
}`
4. click on `tasks.id` on the left: gets me back to the state at (2)
5. click on `tasks.title` on the left: only `tasks.id` appears checked, the query code updates to `{
  tasks {
    id
  }
}`
6. click on `tasks.id` on the left: only `tasks.id` appears checked, the query code updates to `{
  tasks
}` (invalid graphql)
