### ISSUE TITLE
Deselecting last field for query doesn't remove query from explorer code

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#11]
When first selecting a field for a table in the field selection next to GraphiQL:
![image](https://user-images.githubusercontent.com/12881718/159681812-f90dabf7-5923-4556-b8e1-f38c29adc08d.png)
and then unchecking all the fields from that table, the resulting query becomes invalid. It should remove the table query altogether, so the tool never produces an erroring result.

**Comment by mpscholten** [comment]
Fixed
