### ISSUE TITLE
allow executing multiple queries in one request

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#14]
When I write a graphql request with multiple queries, I expect a valid response:
```graphql
{
  users {
    id
  }
  tasks {
    id
  }
}
```

Current behavior:
A 500 Server Error is thrown

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/pull/1392/commits/d0f681ea5ed21917f4e1f285dcd03f74de72136a
