### ISSUE TITLE
remove `overflow:scroll` from `#content` and `.graphiql-explorer-root > div`

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#15]
Replace with `overflow: auto;` to get rid of ugly, dark borders. (GraphiQL view)

**Comment by mpscholten** [comment]
Can you post a screenshot? I don't see any scrollbars (maybe it's a nixOS thing?)

**Comment by jeyj0** [comment]
Chrome (more obvious here):
![image](https://user-images.githubusercontent.com/12881718/159873900-919e990f-9bc1-481e-8a03-c41f2d750783.png)
Firefox:
![Screen Shot 2022-03-24 at 09 26 48](https://user-images.githubusercontent.com/12881718/159874035-12606aae-8777-4bf5-9b53-2b0fd93c2c2a.png)

Tested on NixOS (verified to happen in FF 97 and Chromium 98)

Does not happen on my Mac's Firefox.

Scrollbars on Mac are "invisible" by default (overlayed when necessary, don't take up any space), which makes it appear as if everything is fine there.
