### ISSUE TITLE
GraphiQL Docs color issues

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#17]
- [x] Search is white
    ![image](https://user-images.githubusercontent.com/12881718/159685100-95c32f80-f9fb-49a8-b1c3-9eb4c946a76f.png)
- [ ] Code in docs is green-on-white + docs color (grey) is hard to read
    ![image](https://user-images.githubusercontent.com/12881718/159685306-6b3c3937-a592-4573-a655-0694d8a70b15.png)
- [ ] clickable links are hard to read (blue on dark green) | also: grey during hover is hard to read
    ![image](https://user-images.githubusercontent.com/12881718/159685485-298d9e99-e750-4cc1-b94d-7ecb7dc99874.png)
    ![image](https://user-images.githubusercontent.com/12881718/159685586-e6f1f2c2-ff9b-408d-8eb8-b3f0e1bb5809.png)

**Comment by mpscholten** [comment]
Did some improvements with https://github.com/digitallyinduced/ihp/pull/1392/commits/294ca422d1a0752d1df602670cbf7be63062186d but not everything is fixed yet
