### ISSUE TITLE
Overly complex error for "Address already in use"

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#19]
This is the error that is thrown if 8000/8001 are already in use, which seems overly long and complex for a probably relatively common error:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint vibrant_banach (b72db00e7396d0f1bc7602e1c468a5de6ef48482d54542e38acd6e73d558b826): Error starting userland proxy: listen tcp4 0.0.0.0:8001: bind: address already in use.
```

**Comment by mpscholten** [comment]
This error is from docker directly. I'm not aware of any possible solution on how we can improve the experience here. Any ideas?

**Comment by jeyj0** [comment]
I know. I don't have any ideas right now, but I ran into it and had an issue where my terminal cut off too early, so I didn't see the actual error. I don't think there's much we can do, but I wanted to put it down in case someone has an epiphany.
