### ISSUE TITLE
Switching to Schema deletes WIP query

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/thin-backend#2]
I was working on a little test query and wanted to check something in the Schema. Switching between the tabs deletes the in-progress query, meaning I have to start over.

Could be considered obsolete once introspection is supported, which would allow usage of the `Docs` panel.

**Comment by mpscholten** [comment]
The Docs panel should already work. [While introspection is not working, we manually pass the GraphQL schema to Graphi.](https://github.com/digitallyinduced/ihp/pull/1392/files#diff-29fe75ef75cd3d414d73ce552dee4f3d33117245eafdb7fa42462d63e7da86afR17)

**Comment by jeyj0** [comment]
Earlier it didn't open, but it does now. Maybe we should then just remove the `Schema` tab? What's the use-case for having it?

**Comment by mpscholten** [comment]
The Schema tab is to read through the types and possible operations. I always find this helpful when working with APIs :D

**Comment by jeyj0** [comment]
I mean, that's what the Docs panel is for, isn't it? Only that it's easier to search for things due to being interactive.

**Comment by mpscholten** [comment]
ok got it. yeah then we could think about removing it in the future. For now it's still helpful as you can e.g. copy paste the schema into postman

**Comment by mpscholten** [comment]
Fixed 👍
