### ISSUE TITLE
The logout() function leaves the user at the login page, instead of redirecting to the main website

### ISSUE THREAD

**Issue by jormaj** [digitallyinduced/thin-backend#34]
Currently, the logout() function redirects the user to the thinbackend.com domain, instead of redirecting to the main website.
Since my app features content for logged in users and for not logged in users, I'd like an option to keep users on my website/app after logging out.
I tried some js myself, but didn't get it to work. F.ex. a fetch to the /DeleteSession url won't work since I can't seem to send the SESSION cookie along without triggering a CORS error.

```js
// doesn't delete session
fetch("https://dn.thinbackend.app/DeleteSession",{method:'DELETE'})
// not allowed
fetch("https://dn.thinbackend.app/DeleteSession",{method:'DELETE',credentials:'include'})
```

As briefly discussed with @mpscholten before, work is already being done on implementing seamless authentication functionality (ie allow users to login without leaving the app/website). If that includes seamless logout, then please close this issue :)

**Comment by mpscholten** [comment]
For a quick fix I've added a `redirectBack` argument to the `/DeleteSession` endpoint :)
