### ISSUE TITLE
react type definitions installed from schema type definitions not working

### ISSUE THREAD

**Issue by chadlavi** [digitallyinduced/thin-backend#46]
After making a schema change, I installed new type definitions using the npm install script on the schema type definitions page. After installing this new version of the type definitions, I am getting TS errors in vscode saying that there are no type definitions for `thin-backend/react`.

the npm install command I used (redacted): 

```
npm install --save-dev "https://thin.dev/ShowTypescriptDeclarationFile?typescriptDeclarationFileId=[redacted]&accessToken=[redacted]"
```

The error (pathname edited to relative to project root):
```
Could not find a declaration file for module 'thin-backend/react'. './node_modules/thin-backend/react.js' implicitly has an 'any' type.
  If the 'thin-backend' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/thin-backend'ts(7016)
```

Before installing the type definitions from my latest schema change, everything was working fine. I had previously installed new updates to my type definitions several times for this project, and there were no issues with those versions.

**Comment by chadlavi** [comment]
Not sure what happened, but for some reason the import was written as `thin-backend/react`, but it needed to be `thin-backend-react`. Not sure how this got changed, but fixing the imports in my files corrected this issue.

**Comment by mpscholten** [comment]
Thanks for reporting this 👍  The `thin-backend/react` module was just moved to a new `thin-backend-react` package a few days ago and we deployed an update to the typescript generation yesterday :) I've already updated all project templates, but if you've created the project with an older version of the template it's still using the `thin-backend/react` imports 👍

**Comment by chadlavi** [comment]
Aha! Well yes I suppose that would do it then. Thanks for the follow up.
