### ISSUE TITLE
Todo App Link `404` in README.md Example Apps Section

### ISSUE THREAD

**Issue by nelsonic** [digitallyinduced/thin-backend#50]
Hey! 👋 
Was just reading through your docs [looking good!] but noted that:
https://github.com/digitallyinduced/thin-backend/blame/6e376d3861370e58aea83dfe5eabf8f0a2924ed0/README.md#L221
links to: https://github.com/digitallyinduced/ihp-backend-todo-app which is `404`
![image](https://user-images.githubusercontent.com/194400/174014782-df00fcb7-950d-481f-bcbb-e3e9e7f29156.png)

Should be: https://github.com/digitallyinduced/thin-backend-todo-app
![image](https://user-images.githubusercontent.com/194400/174015172-45e3f6ee-9fe4-40fa-b8f8-6e414211b126.png)

**Comment by mpscholten** [comment]
Thanks, good catch 👍
