### ISSUE TITLE
Renaming table migration fails

### ISSUE THREAD

**Issue by jolonf** [digitallyinduced/thin-backend#66]
When a table is renamed the migration renames the table first, but refers to the original name in subsequent statements, e.g. renaming `media` to `artefacts` produces the following migration which won't run:

```sql
ALTER TABLE media RENAME TO artefacts;
DROP INDEX media_created_at_index;
DROP INDEX media_user_id_index;
ALTER TABLE media DROP CONSTRAINT media_ref_user_id;
DROP POLICY "Users can manage their media" ON media;
```

**Comment by mpscholten** [comment]
Thanks! I can reproduce the issue 👍
