### ISSUE TITLE
Deleting a table tries to drop table before its policy

### ISSUE THREAD

**Issue by pythia-dev** [digitallyinduced/thin-backend#69]
Steps to reproduce:

1. Create a new table, and apply the change to the database by performing the generated migration.
2. In the Schema tab, right click on the table name and click Delete Table. Accept the warning.
3. Click "Run Migrations" and attempt to run the migration.

Expected result: The migration runs successfully and drops the table.
Actual result: An error is displayed- _relation "test" does not exist_

It's producing this SQL:
```
DROP TABLE test;
DROP POLICY "Users can manage their test" ON test;
```

Presumably dropping the policy needs to be done first, as this SQL seems to work:
```
DROP POLICY "Users can manage their test" ON test;
DROP TABLE test;
```

**Comment by mpscholten** [comment]
Thanks for reporting 👍 I just pushed a fix and will deploy it to prod now
