### ISSUE TITLE
Default yarn command to install types doesn't seem to work with yarn 3.2.0

### ISSUE THREAD

**Issue by ItsMeTazz** [digitallyinduced/thin-backend#71]
Hi frens :) 

First timer with Thin, really looking forward to testing it!

Running into some difficulties to run the following command in my NextJS project: 
`yarn add --dev "https://thin.dev/types/....../......."`

Getting: 
`Usage Error: It seems you are trying to add a package using a https:... url; we now require package names to be explicitly specified.`

I haven't found the right yarn command yet. I'm using yarn 3.2.0.
Can anybody help?

Thanks and cheers!

**Comment by mpscholten** [comment]
How did you solve this?
